### ISSUE TITLE
Alternative online exporter

### ISSUE THREAD

**Issue by lcandy2** [ivnvxd/arc-export#6]
https://arc-export.vercel.app/

And here is the GitHub repo [lcandy2/arc-bookmarks-export](https://github.com/lcandy2/arc-bookmarks-export)

Fully open source and exporting locally, deployed by vercel which trustable.

**Comment by ivnvxd** [comment]
That's great! But why would one prefer the option of installing dependencies, raising the server, and running it through a web interface, instead of just running a single script with a single command? And by the way, you need to install pnpm first, which unlike python is not pre-installed.

Vercel is just one of the hosting platforms. It is in no way responsible for what is hosted on it. I don't understand what kind of trust you're talking about.

But in any case, it's great to have alternatives. Good job!

**Comment by lcandy2** [comment]
Cause not everyone understands python and cli? that's why i am make an alternative.

Vercel is trustable is because you could see the deployment from the repo, the website you see will only be the one in the repo. also i can changed to the github pages sometime.

**Comment by ivnvxd** [comment]
It's great that you did this. Having alternatives is always a good thing!
